import type { CronJobRow } from '@hermes/plugin-sdk'

/** A `cron.manage {action: 'list'}` row at its zero value; a test states only what it asserts on. */
export const cronJobRow = (over: Partial<CronJobRow> = {}): CronJobRow => ({
  job_id: '',
  name: '',
  skill: null,
  skills: [],
  prompt_preview: '',
  model: null,
  provider: null,
  base_url: null,
  schedule: '',
  repeat: null,
  deliver: null,
  next_run_at: null,
  last_run_at: null,
  last_status: null,
  last_delivery_error: null,
  last_delivery_unverified: null,
  last_fire_error: null,
  last_error: null,
  enabled: true,
  state: null,
  paused_at: null,
  paused_reason: null,
  script: null,
  reasoning_effort: null,
  monitor_script: null,
  monitor_url: null,
  monitor_state: null,
  no_agent: null,
  enabled_toolsets: null,
  workdir: null,
  continuity: null,
  context_from: null,
  attach_to_session: null,
  ...over
})
