"""Render ``tui_gateway/contracts`` into TypeScript and OpenRPC.

Python-only (the Python CI lane has no Node): Pydantic's ``model_json_schema()`` output is walked
by a deliberately small JSON-Schema-subset renderer. Unsupported constructs fail generation so a
contract is corrected at its producer rather than weakened in generated TypeScript.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import OrderedDict
from pathlib import Path
from typing import Any, get_args, get_origin

from pydantic import BaseModel, TypeAdapter
from pydantic.json_schema import GenerateJsonSchema

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


def _catalog():
    """Import all contract topics before reading their registration tables."""
    from tui_gateway import contracts  # noqa: F401  (fills the registration tables)
    from tui_gateway.contracts.registry import EVENTS, METHODS, SERVER_REQUESTS

    return METHODS, SERVER_REQUESTS, EVENTS


TS_FILENAME = "gateway-contract.generated.ts"
OPENRPC_FILENAME = "gateway-contract.openrpc.json"
TS_OUT = ROOT / "apps" / "shared" / "src" / TS_FILENAME
OPENRPC_OUT = ROOT / "apps" / "shared" / "src" / OPENRPC_FILENAME

HEADER = (
    "// GENERATED by scripts/gen_gateway_contracts.py from tui_gateway/contracts — DO NOT EDIT.\n"
    "// Regenerate: .venv/bin/python scripts/gen_gateway_contracts.py\n"
    "// tests/tui_gateway/contracts/test_generated.py checks the renderer.\n"
)

_IGNORED = {"title", "default", "description", "discriminator"}
_FORBIDDEN = {
    "allOf",
    "contains",
    "contentEncoding",
    "contentMediaType",
    "contentSchema",
    "dependentRequired",
    "dependentSchemas",
    "else",
    "exclusiveMaximum",
    "exclusiveMinimum",
    "format",
    "if",
    "maxContains",
    "maxItems",
    "maximum",
    "maxLength",
    "maxProperties",
    "minContains",
    "minItems",
    "minimum",
    "minLength",
    "minProperties",
    "multipleOf",
    "not",
    "pattern",
    "patternProperties",
    "prefixItems",
    "propertyNames",
    "then",
    "unevaluatedItems",
    "unevaluatedProperties",
    "uniqueItems",
}
_ALLOWED = {
    "$defs",
    "$ref",
    "additionalProperties",
    "anyOf",
    "const",
    "enum",
    "items",
    "oneOf",
    "properties",
    "required",
    "type",
}
_JSON_VALUE_TS = "string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue }"


class RenderError(ValueError):
    """A contract uses a JSON-Schema feature that has no safe TS wire representation."""


class _Schema(GenerateJsonSchema):
    """Stable ``$defs`` naming: the model's class name (no module qualifiers)."""

    def normalize_name(self, name: str) -> str:
        return re.sub(r"[^A-Za-z0-9_]", "_", name)


def _pascal(name: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in re.split(r"[._-]", name) if part)


def _type_name(slot: str) -> str:
    """Name a top-level class from its source model, unions from the wire method."""
    words = slot.rsplit(".", 1)
    if len(words) == 2 and words[1] in {"params", "result", "payload"}:
        return _pascal(words[0]) + words[1].capitalize()
    return _pascal(slot)


def _ref_name(ref: str) -> str:
    if not ref.startswith("#/$defs/") and not ref.startswith("#/components/schemas/"):
        raise RenderError(f"unsupported reference {ref!r}")
    return ref.rsplit("/", 1)[1]


def _schema_for(tp: Any) -> dict:
    """Return one schema with local ``$defs`` for a contract slot."""
    return TypeAdapter(tp).json_schema(
        mode="serialization", schema_generator=_Schema, ref_template="#/$defs/{model}"
    )


def _inbound_name(name: str) -> str:
    return name if name == "JsonValue" else f"{name}Input"


def _is_json_value(tp: Any) -> bool:
    """Pydantic emits JsonValue's sanctioned recursive alias as an empty ``$defs`` entry."""
    return getattr(tp, "__name__", None) == "JsonValue"


def _field_type(model: type[BaseModel], name: str) -> Any | None:
    field = model.model_fields.get(name)
    return field.annotation if field is not None else None


def _json_value_def_names(tp: Any) -> set[str]:
    """Map the sole sanctioned recursive JsonValue empty $def to its generated name."""
    return {
        name
        for name, definition in _schema_for(tp).get("$defs", {}).items()
        if definition == {} and name == "JsonValue"
    }


def _error(path: str, detail: str) -> None:
    raise RenderError(f"{path}: {detail}")


def _schema_ref_name(schema: dict) -> str | None:
    ref = schema.get("$ref")
    return _ref_name(ref) if isinstance(ref, str) else None


def _is_json_value_type(tp: Any) -> bool:
    if _is_json_value(tp):
        return True
    return get_origin(tp) is not None and any(_is_json_value_type(item) for item in get_args(tp))


def _validate_schema(
    schema: dict,
    *,
    path: str,
    definitions: dict[str, dict],
    models: dict[str, type[BaseModel]],
    current_model: type[BaseModel] | None,
    checked_defs: set[str],
    json_value_defs: set[str],
) -> None:
    """Reject constructs that cannot describe a closed TypeScript wire shape."""
    for key in schema:
        if key in _IGNORED or key in _ALLOWED:
            continue
        if key in _FORBIDDEN:
            _error(path, f"keyword {key!r} is not representable in TypeScript")
        _error(path, f"unsupported JSON Schema keyword {key!r}")

    reference = _schema_ref_name(schema)
    if reference is not None:
        if reference in checked_defs:
            return
        if reference not in definitions:
            _error(path, f"unknown schema definition {reference!r}")
        checked_defs.add(reference)
        definition = definitions[reference]
        if not definition:
            if reference in json_value_defs:
                return
            _error(path, "empty schema is only allowed for JsonValue")
        _validate_schema(
            definition,
            path=reference,
            definitions=definitions,
            models=models,
            current_model=models.get(reference) or current_model,
            checked_defs=checked_defs,
            json_value_defs=json_value_defs,
        )
        return

    if not schema or set(schema) <= _IGNORED:
        _error(path, "empty schema is only allowed for JsonValue")

    additional = schema.get("additionalProperties")
    if additional is True:
        _error(path, "additionalProperties: true is not representable in TypeScript")
    if isinstance(additional, dict):
        _validate_schema(
            additional,
            path=f"{path}.*",
            definitions=definitions,
            models=models,
            current_model=None,
            checked_defs=checked_defs,
            json_value_defs=json_value_defs,
        )

    if "prefixItems" in schema:
        _error(path, "keyword 'prefixItems' is not representable in TypeScript")
    if schema.get("type") == "array" and "items" not in schema:
        _error(path, "array without items is not representable in TypeScript")

    for index, member in enumerate(schema.get("anyOf", ())):
        _validate_schema(
            member,
            path=f"{path}.union[{index}]",
            definitions=definitions,
            models=models,
            current_model=current_model,
            checked_defs=checked_defs,
            json_value_defs=json_value_defs,
        )
    for index, member in enumerate(schema.get("oneOf", ())):
        _validate_schema(
            member,
            path=f"{path}.union[{index}]",
            definitions=definitions,
            models=models,
            current_model=current_model,
            checked_defs=checked_defs,
            json_value_defs=json_value_defs,
        )
    if "items" in schema:
        _validate_schema(
            schema["items"],
            path=f"{path}.items",
            definitions=definitions,
            models=models,
            current_model=None,
            checked_defs=checked_defs,
            json_value_defs=json_value_defs,
        )

    for name, field_schema in schema.get("properties", {}).items():
        field_type = _field_type(current_model, name) if current_model is not None else None
        if _is_json_value_type(field_type):
            continue
        _validate_schema(
            field_schema,
            path=f"{path}.{name}",
            definitions=definitions,
            models=models,
            current_model=None,
            checked_defs=checked_defs,
            json_value_defs=json_value_defs,
        )


def _validate_contract_type(tp: Any, *, owner: str) -> None:
    """Validate a slot independently so failures identify its model and field."""
    schema = _schema_for(tp)
    definitions = schema.pop("$defs", {})
    json_value_defs = _json_value_def_names(tp)
    models = {model.__name__: model for model in _models_in(tp)}

    _validate_schema(
        schema,
        path=tp.__name__ if isinstance(tp, type) and issubclass(tp, BaseModel) else owner,
        definitions=definitions,
        models=models,
        current_model=tp if isinstance(tp, type) and issubclass(tp, BaseModel) else None,
        checked_defs=set(),
        json_value_defs=json_value_defs,
    )


def _models_in(tp: Any, seen: set[type[BaseModel]] | None = None) -> tuple[type[BaseModel], ...]:
    """Find models through fields as well as nested unions, without looping on recursive types."""
    seen = seen if seen is not None else set()
    if isinstance(tp, type) and issubclass(tp, BaseModel):
        if tp in seen:
            return ()
        seen.add(tp)
        nested = tuple(
            model
            for field in tp.model_fields.values()
            for model in _models_in(field.annotation, seen)
        )
        return (tp, *nested)
    if get_origin(tp) is not None:
        return tuple(model for item in get_args(tp) for model in _models_in(item, seen))
    return ()


class ContractSchemas:
    """Collect all slots into one stable definition table and preserve wire direction."""

    def __init__(self) -> None:
        self.defs: OrderedDict[str, dict] = OrderedDict()
        self.inbound_defs: set[str] = set()
        self._classes: dict[str, type[BaseModel]] = {}
        self._models: dict[str, type[BaseModel]] = {}
        self.methods: OrderedDict[str, dict[str, dict]] = OrderedDict()
        self.server_requests: OrderedDict[str, dict[str, dict]] = OrderedDict()
        self.events: OrderedDict[str, dict[str, dict | None]] = OrderedDict()

    def _validate_defs(self) -> None:
        for name, definition in self.defs.items():
            if not definition and name == "JsonValue":
                continue
            _validate_schema(
                definition,
                path=name,
                definitions=self.defs,
                models=self._models,
                current_model=self._models.get(name),
                checked_defs={name},
                json_value_defs={"JsonValue"},
            )

    def _register_classes(self, tp: Any, owner: str, *, inbound: bool) -> None:
        for model in _models_in(tp):
            name = _inbound_name(model.__name__) if inbound else model.__name__
            existing = self._classes.get(name)
            if existing is not None and existing is not model:
                raise RenderError(f"{owner}: duplicate class name {name!r}")
            self._classes[name] = model
            self._models[name] = model

    def add(self, tp: Any, slot: str, *, inbound: bool) -> dict:
        """Return the slot's ``$ref`` schema after folding its definitions into the shared table."""
        _validate_contract_type(tp, owner=slot)
        self._register_classes(tp, slot, inbound=inbound)
        schema = _schema_for(tp)
        for name, definition in schema.pop("$defs", {}).items():
            existing = self.defs.get(name)
            if existing is not None and existing != definition:
                if name not in self._classes:
                    raise RenderError(f"{slot}: duplicate class name {name!r}")
                continue
            if existing is None:
                self.defs[name] = definition

        if "$ref" not in schema:
            # Unions and other non-model top levels need a readable, stable public symbol.
            name = _pascal(slot)
            schema.pop("title", None)
            existing = self.defs.get(name)
            # A payload class that another model also nests arrived first via that model's ``$defs``,
            # ``title`` included; the same class is one definition, not a collision.
            if existing is not None and {k: v for k, v in existing.items() if k != "title"} != schema:
                raise RenderError(f"{slot}: duplicate anonymous schema name {name!r}")
            if existing is None:
                self.defs[name] = schema
            schema = {"$ref": f"#/$defs/{name}"}

        top_name = _ref_name(schema["$ref"])
        if inbound:
            input_name = _type_name(slot)
            if input_name != top_name:
                existing = self.defs.get(input_name)
                if existing is not None and existing != self.defs[top_name]:
                    raise RenderError(f"{slot}: duplicate inbound class name {input_name!r}")
                if existing is None:
                    self.defs[input_name] = self.defs[top_name]
                    source_model = self._models.get(top_name)
                    if source_model is not None:
                        self._models[input_name] = source_model
                schema = {"$ref": f"#/$defs/{input_name}"}
                top_name = input_name
            self.inbound_defs.add(top_name)
        return schema


def collect() -> ContractSchemas:
    """Collect every contract model exactly once, naming anonymous slots from their wire name."""
    methods, server_requests, events = _catalog()
    schemas = ContractSchemas()
    for method in sorted(methods.values(), key=lambda entry: entry.name):
        schemas.methods[method.name] = {
            "params": schemas.add(method.params, f"{method.name}.params", inbound=True),
            "result": schemas.add(method.result, f"{method.name}.result", inbound=False),
        }
    for request in sorted(server_requests.values(), key=lambda entry: entry.name):
        schemas.server_requests[request.name] = {
            "params": schemas.add(request.params, f"{request.name}.params", inbound=False),
            "result": schemas.add(request.result, f"{request.name}.result", inbound=True),
        }
    for event_contract in sorted(events.values(), key=lambda entry: entry.name):
        schemas.events[event_contract.name] = {
            "payload": (
                schemas.add(event_contract.payload, f"{event_contract.name}.payload", inbound=False)
                if event_contract.payload is not None
                else None
            )
        }
    schemas._validate_defs()
    return schemas


# ── TypeScript rendering ─────────────────────────────────────────────────────────────────────────


class Renderer:
    def __init__(self, defs: dict[str, dict], inbound_defs: set[str] | None = None):
        self.defs = defs
        self.inbound_defs = inbound_defs or set()
        self.emitted: OrderedDict[str, str] = OrderedDict()

    def type_of(self, schema: dict, *, path: str, inline_depth: int = 0) -> str:
        return " | ".join(self.members_of(schema, path=path, inline_depth=inline_depth))

    def members_of(self, schema: dict, *, path: str, inline_depth: int = 0) -> list[str]:
        """Top-level union members, so emit sites can apply prettier's union line-wrap rule."""
        if "$ref" in schema:
            name = _ref_name(schema["$ref"])
            self.ensure(name)
            return [name]
        if "const" in schema:
            return [_lit(schema["const"])]
        if "enum" in schema:
            return [_lit(value) for value in schema["enum"]]
        if "anyOf" in schema or "oneOf" in schema:
            variants = schema.get("anyOf") or schema.get("oneOf") or []
            return list(
                dict.fromkeys(
                    member
                    for index, variant in enumerate(variants)
                    for member in self.members_of(
                        variant, path=f"{path}.union[{index}]", inline_depth=inline_depth
                    )
                )
            )
        type_ = schema.get("type")
        if isinstance(type_, list):
            return [
                member
                for item in type_
                for member in self.members_of({**schema, "type": item}, path=path, inline_depth=inline_depth)
            ]
        if type_ == "string":
            return ["string"]
        if type_ in ("integer", "number"):
            return ["number"]
        if type_ == "boolean":
            return ["boolean"]
        if type_ == "null":
            return ["null"]
        if type_ == "array":
            inner = self.type_of(schema["items"], path=f"{path}.items", inline_depth=inline_depth)
            return [f"({inner})[]" if " | " in inner else f"{inner}[]"]
        if type_ == "object" or "properties" in schema or "additionalProperties" in schema:
            return [self.object_literal(schema, path=path, depth=inline_depth)]
        raise RenderError(f"{path}: unsupported JSON Schema construct {json.dumps(schema)[:200]}")

    def object_literal(self, schema: dict, *, path: str, depth: int) -> str:
        properties = schema.get("properties")
        additional = schema.get("additionalProperties")
        if not properties:
            if additional is False:
                return "Record<string, never>"
            if isinstance(additional, dict):
                value = self.type_of(additional, path=f"{path}.*", inline_depth=depth + 1)
                return f"Record<string, {value}>"
            raise RenderError(f"{path}: empty object is not representable in TypeScript")
        required = set(schema.get("required", ()))
        inbound = path.split(".", 1)[0] in self.inbound_defs
        indent = "  " * (depth + 1)
        lines = ["{"]
        for key, subschema in properties.items():
            optional = "?" if inbound and key not in required else ""
            members = self.members_of(subschema, path=f"{path}.{key}", inline_depth=depth + 1)
            lines.append(_wrap_union(f"{indent}{_prop(key)}{optional}:", members, indent))
        lines.append("  " * depth + "}")
        return "\n".join(lines)

    def ensure(self, name: str) -> None:
        if name in self.emitted:
            return
        if name not in self.defs:
            raise RenderError(f"unknown schema definition {name!r}")
        self.emitted[name] = ""  # cycle guard
        schema = self.defs[name]
        if name == "JsonValue":
            if schema:
                raise RenderError("JsonValue: expected the recursive JsonValue empty schema")
            self.emitted[name] = f"export type JsonValue = {_JSON_VALUE_TS}\n"
            return
        if not schema:
            raise RenderError(f"{name}: empty schema is only allowed for JsonValue")
        doc = _doc(schema.get("description"))
        if "enum" in schema:
            members = self.members_of({"enum": schema["enum"]}, path=name)
            body = _wrap_union(f"export type {name} =", members) + "\n"
        elif schema.get("type") == "object" and schema.get("properties"):
            body = f"export interface {name} {self.object_literal(schema, path=name, depth=0)}\n"
        else:
            body = _wrap_union(f"export type {name} =", self.members_of(schema, path=name)) + "\n"
        self.emitted[name] = doc + body

    def render_all(self) -> OrderedDict[str, str]:
        self.emitted.clear()
        for name in self.defs:
            self.ensure(name)
        return self.emitted


_IDENT = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")
_PRINT_WIDTH = 120  # .prettierrc printWidth


def _wrap_union(prefix: str, members: list[str], indent: str = "") -> str:
    """Prettier's union layout: inline, one continuation line, or one `| member` line each.
    Members that already span lines keep their own layout; the prettier diff gate covers them."""
    union = " | ".join(members)
    inline = f"{prefix} {union}"
    if len(members) < 2 or "\n" in union or len(inline) <= _PRINT_WIDTH:
        return inline
    if len(indent) + 2 + len(union) <= _PRINT_WIDTH:
        return f"{prefix}\n{indent}  {union}"
    return f"{prefix}\n" + "\n".join(f"{indent}  | {member}" for member in members)


def _prop(key: str) -> str:
    return key if _IDENT.match(key) else _lit(key)


def _const_items(names: list[str]) -> str:
    return ",\n".join(f"  {_lit(name)}" for name in names) + "\n"


def _lit(value: object) -> str:
    """A TS literal in the repo's prettier style (single quotes, `.prettierrc` singleQuote), so the
    committed file needs no Node-side formatting pass."""
    if isinstance(value, str):
        return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"
    return json.dumps(value)


def _doc(text: str | None, indent: str = "") -> str:
    if not text:
        return ""
    return f"{indent}/** {' '.join(text.split())} */\n"


_TAIL_INTERFACES = ("RpcMethods", "ServerRequestMap", "BackendGatewayEventMap",
                    "RpcMethod", "ServerRequestMethod", "BackendGatewayEventName")


def render_ts() -> str:
    methods, server_requests, events = _catalog()
    schemas = collect()
    taken = [name for name in _TAIL_INTERFACES if name in schemas.defs]
    if taken:
        raise RenderError(f"contract class names collide with generated interfaces: {taken}")
    renderer = Renderer(schemas.defs, schemas.inbound_defs)
    for name in schemas.defs:
        renderer.ensure(name)
    if "JsonValue" in renderer.emitted:
        renderer.emitted.move_to_end("JsonValue", last=False)

    out = [HEADER, "/* eslint-disable */\n", "// ── Types ──\n"]
    out.extend(renderer.emitted.values())

    out.append("\n// ── Client→server methods ──\n")
    out.append("export interface RpcMethods {\n")
    for method in sorted(methods.values(), key=lambda entry: entry.name):
        out.append(_doc(method.doc, "  "))
        spec = schemas.methods[method.name]
        params = _ref_name(spec["params"]["$ref"])
        result = _ref_name(spec["result"]["$ref"])
        out.append(f"  {_prop(method.name)}: {{ params: {params}; result: {result} }}\n")
    out.append("}\n")
    out.append("export type RpcMethod = keyof RpcMethods\n")
    out.append(
        "export const RPC_METHODS = [\n"
        + _const_items(sorted(methods))
        + "] as const satisfies readonly RpcMethod[]\n"
    )

    out.append("\n// ── Server→client requests ──\n")
    out.append("export interface ServerRequestMap {\n")
    for request in sorted(server_requests.values(), key=lambda entry: entry.name):
        out.append(_doc(request.doc, "  "))
        spec = schemas.server_requests[request.name]
        params = _ref_name(spec["params"]["$ref"])
        result = _ref_name(spec["result"]["$ref"])
        out.append(f"  {_prop(request.name)}: {{ params: {params}; result: {result} }}\n")
    out.append("}\n")
    out.append("export type ServerRequestMethod = keyof ServerRequestMap\n")
    out.append(
        "export const SERVER_REQUEST_METHODS = [\n"
        + _const_items(sorted(server_requests))
        + "] as const satisfies readonly ServerRequestMethod[]\n"
    )

    out.append("\n// ── Notifications (`event` frames) ──\n")
    out.append("export interface BackendGatewayEventMap {\n")
    for event_contract in sorted(events.values(), key=lambda entry: entry.name):
        out.append(_doc(event_contract.doc, "  "))
        payload = schemas.events[event_contract.name]["payload"]
        payload_name = _ref_name(payload["$ref"]) if payload is not None else "Record<string, never>"
        out.append(f"  {_prop(event_contract.name)}: {payload_name}\n")
    out.append("}\n")
    out.append("export type BackendGatewayEventName = keyof BackendGatewayEventMap\n")
    out.append(
        "export const GATEWAY_EVENT_TYPES = [\n"
        + _const_items(sorted(events))
        + "] as const satisfies readonly BackendGatewayEventName[]\n"
    )
    return "".join(out)


def _tidy(text: str) -> str:
    """No trailing whitespace, single trailing newline (matches prettier)."""
    return "\n".join(line.rstrip() for line in text.splitlines()).rstrip("\n") + "\n"


# ── OpenRPC rendering ────────────────────────────────────────────────────────────────────────────


def _openrpc_schema(schema: dict) -> dict:
    """OpenRPC schemas live under components.schemas, not a local ``$defs`` table."""
    return json.loads(json.dumps(schema).replace("#/$defs/", "#/components/schemas/"))


def _descriptors(schemas: ContractSchemas, top: dict) -> list[dict]:
    schema = schemas.defs[_ref_name(top["$ref"])]
    properties = schema.get("properties")
    if properties is None:
        return [{"name": "params", "required": True, "schema": _openrpc_schema(top)}]
    required = set(schema.get("required", ()))
    return [
        {"name": name, "required": name in required, "schema": _openrpc_schema(field)}
        for name, field in properties.items()
    ]


def render_openrpc() -> str:
    methods, server_requests, events = _catalog()
    schemas = collect()

    def entry(name: str, spec: dict[str, dict], *, result: bool, summary: str) -> dict:
        rendered = {
            "name": name,
            "summary": " ".join(summary.split()),
            "paramStructure": "by-name",
            "params": _descriptors(schemas, spec["params"]),
        }
        if result:
            rendered["result"] = {"name": "result", "schema": _openrpc_schema(spec["result"])}
        return rendered

    event_types = [
        {
            "type": event_contract.name,
            "wireMethod": "event",
            "payload": _openrpc_schema(payload)
            if (payload := schemas.events[event_contract.name]["payload"]) is not None
            else {"type": "object", "additionalProperties": False},
        }
        for event_contract in sorted(events.values(), key=lambda item: item.name)
    ]
    document = {
        "openrpc": "1.3.2",
        "info": {
            "title": "Hermes TUI/Desktop gateway",
            "version": "1",
            "description": "Generated from tui_gateway/contracts by scripts/gen_gateway_contracts.py.",
        },
        "methods": [
            entry(method.name, schemas.methods[method.name], result=True, summary=method.doc)
            for method in sorted(methods.values(), key=lambda item: item.name)
        ],
        "components": {
            "schemas": {
                name: _openrpc_schema(schema)
                for name, schema in schemas.defs.items()
            }
        },
        "x-hermes-server-requests": [
            entry(request.name, schemas.server_requests[request.name], result=True, summary=request.doc)
            for request in sorted(server_requests.values(), key=lambda item: item.name)
        ],
        "x-hermes-notifications": [
            {
                "name": "event",
                "paramStructure": "by-name",
                "params": [
                    {"name": "type", "required": True, "schema": {"type": "string", "enum": sorted(events)}},
                    {"name": "session_id", "required": True, "schema": {"type": "string"}},
                    {"name": "seq", "required": False, "schema": {"type": "integer"}},
                    {"name": "payload", "required": True, "schema": {"type": "object"}},
                ],
            }
        ],
        "x-hermes-event-types": event_types,
        "x-hermes-client-notifications": [],
    }
    return json.dumps(document, indent=2, sort_keys=False) + "\n"


def render_all(out_dir: Path | None = None) -> dict[Path, str]:
    out_dir = out_dir or TS_OUT.parent
    return {
        out_dir / TS_FILENAME: _tidy(render_ts()),
        out_dir / OPENRPC_FILENAME: render_openrpc(),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if output differs from rendered contracts")
    parser.add_argument("--out-dir", type=Path, default=TS_OUT.parent, help="directory for generated files")
    args = parser.parse_args(argv)

    stale: list[Path] = []
    for path, text in render_all(args.out_dir).items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        if args.check:
            stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT) if path.is_relative_to(ROOT) else path}")
    if stale:
        for path in stale:
            display = path.relative_to(ROOT) if path.is_relative_to(ROOT) else path
            print(f"stale: {display} — run scripts/gen_gateway_contracts.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
