"""Automatic background review must not treat compaction-summary carriers as user evidence.

``role=user`` on a Hermes compaction handoff is transport compatibility, not authorship: the
body was generated by Hermes, so an unattended memory-capable review fork must not see it as
candidate evidence for durable memory writes. These tests drive the real
``AIAgent._spawn_background_review`` -> fork ``run_conversation`` boundary and assert on the
``conversation_history`` the review model would actually see.
"""

from __future__ import annotations

import copy
import json
import os
import sys
import threading
from types import SimpleNamespace
from unittest.mock import patch

import pytest

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

import run_agent as run_agent_module  # noqa: E402
import agent.background_review as bg  # noqa: E402
from agent.context_compressor import (  # noqa: E402
    COMPRESSED_SUMMARY_HAS_USER_TURN_KEY,
    COMPRESSED_SUMMARY_METADATA_KEY,
    LEGACY_SUMMARY_PREFIX,
    SUMMARY_PREFIX,
    _HISTORICAL_SUMMARY_PREFIXES,
    _MERGED_PRIOR_CONTEXT_HEADER,
    _MERGED_SUMMARY_DELIMITER,
    _SUMMARY_END_MARKER,
)
from run_agent import AIAgent  # noqa: E402

_SUMMARY_MARKER = "SUMMARY_ONLY_PREF_7f3a9"
_TAIL_MARKER = "TAIL_DIRECT_STATEMENT_2b8c1"
_LIVE_MERGED_MARKER = "LIVE_MERGED_ASK_4d5e6"

# Carriers a real snapshot can carry: every frozen prefix generation (byte-pinned upstream),
# and a metadata-marked row whose text matches none of them.
_STANDALONE_CARRIER_CONTENTS = [
    pytest.param(prefix, id=name)
    for name, prefix in (
        [("current", SUMMARY_PREFIX), ("legacy", LEGACY_SUMMARY_PREFIX)]
        + [(f"historical-{i}", p) for i, p in enumerate(_HISTORICAL_SUMMARY_PREFIXES)]
    )
]


def _summary_body() -> str:
    return (
        "\n## Historical Task Snapshot\n"
        f"User asked: always deploy with {_SUMMARY_MARKER} enabled.\n\n"
        "## Resolved State\nCompleted earlier.\n\n" + _SUMMARY_END_MARKER
    )


def _carrier(prefix: str, marked: bool = True) -> dict:
    row = {
        "role": "user",
        "content": prefix + _summary_body(),
    }
    if marked:
        row[COMPRESSED_SUMMARY_METADATA_KEY] = True
    return row


def _row_text(row) -> str:
    """All text a review model would see in one replayed history row."""
    if not isinstance(row, dict):
        return str(row)
    return bg._msg_text(row)


def _history_text(history) -> str:
    return "\n".join(_row_text(row) for row in history or [])


def _snapshot_with_carrier(carrier: dict) -> list:
    return [
        {"role": "user", "content": "set up the staging deploy"},
        {"role": "assistant", "content": "staging deploy is configured"},
        carrier,
        {"role": "assistant", "content": "handoff noted"},
        {"role": "user", "content": f"please keep using {_TAIL_MARKER} for these checks"},
    ]


class _ImmediateThread:
    def __init__(self, *, target, daemon=None, name=None):
        self._target = target

    def start(self):
        self._target()


def _bare_agent() -> AIAgent:
    agent = object.__new__(AIAgent)
    agent.model = "fake-model"
    agent.platform = "telegram"
    agent.provider = "openai"
    agent.base_url = ""
    agent.api_key = ""
    agent.api_mode = ""
    agent.session_id = "test-session"
    agent._parent_session_id = ""
    agent._credential_pool = None
    agent._memory_store = object()
    agent._memory_enabled = True
    agent._user_profile_enabled = False
    agent._cached_system_prompt = "test-cached-system-prompt"
    import datetime as _dt
    agent.session_start = _dt.datetime(2026, 1, 1, 12, 0, 0)
    agent._MEMORY_REVIEW_PROMPT = "review memory"
    agent._SKILL_REVIEW_PROMPT = "review skills"
    agent._COMBINED_REVIEW_PROMPT = "review both"
    agent.background_review_callback = None
    agent.status_callback = None
    agent._safe_print = lambda *_args, **_kwargs: None
    agent._background_review_agent = None
    agent._background_review_run = None
    agent._background_review_lock = threading.Lock()
    agent._active_children = []
    agent._active_children_lock = threading.Lock()
    return agent


def _drive_spawn(monkeypatch, snapshot, on_run=None, agent=None, **kwargs):
    """Drive the real spawn path with a capturing fork; return the ``run_conversation`` kwargs."""
    captured = {}

    class FakeReviewAgent:
        def __init__(self, **_kw):
            self._session_messages = []

        def run_conversation(self, **kw):
            captured.update(kw)
            if on_run is not None:
                on_run()

        def interrupt(self, message=None):
            pass

        def release_clients(self):
            pass

        def shutdown_memory_provider(self):
            pass

        def close(self):
            pass

    monkeypatch.setattr(run_agent_module, "AIAgent", FakeReviewAgent)
    monkeypatch.setattr(run_agent_module.threading, "Thread", _ImmediateThread)

    agent = agent or _bare_agent()
    AIAgent._spawn_background_review(agent, messages_snapshot=snapshot, **kwargs)
    return captured


def _drive_spawn_routed(monkeypatch, snapshot, **kwargs):
    """Same path but the fork resolves to a different model, so the snapshot is digested."""
    captured = {}
    fork = SimpleNamespace(
        _memory_enabled=True, _user_profile_enabled=False, _session_messages=[],
        run_conversation=lambda **kw: captured.update(kw),
        interrupt=lambda *a, **k: None, release_clients=lambda: None,
    )

    def fake_build(agent, task_cfg=None, *, max_iterations, write_origin="background_review"):
        return fork, {}, True  # routed=True

    monkeypatch.setattr(run_agent_module.threading, "Thread", _ImmediateThread)
    with patch.object(bg, "build_cache_parity_fork", fake_build):
        agent = _bare_agent()
        AIAgent._spawn_background_review(agent, messages_snapshot=snapshot, **kwargs)
    return captured


class TestSummaryEvidenceWithheld:
    """R1: an unattended memory-capable review must not see summary-only payload."""

    @pytest.mark.parametrize("marked", [True, False])
    @pytest.mark.parametrize("prefix", _STANDALONE_CARRIER_CONTENTS)
    def test_summary_body_never_reaches_memory_review(self, monkeypatch, prefix, marked):
        # marked=False is the session-store round-trip shape: wire sanitizers and some
        # persistence paths strip the marker, leaving detection to the content prefix.
        captured = _drive_spawn(
            monkeypatch,
            _snapshot_with_carrier(_carrier(prefix, marked=marked)),
            review_memory=True, review_skills=False,
        )
        history = captured.get("conversation_history", [])
        text = _history_text(history)
        assert _SUMMARY_MARKER not in text
        stub = bg._REVIEW_SUMMARY_EVIDENCE_STUB
        assert sum(stub in _row_text(r) for r in history) == 1
        assert _TAIL_MARKER in text

    def test_metadata_marked_carrier_with_unrecognised_text(self, monkeypatch):
        carrier = {
            "role": "user",
            "content": f"generated recap text with no known prefix mentioning {_SUMMARY_MARKER}",
            COMPRESSED_SUMMARY_METADATA_KEY: True,
        }
        captured = _drive_spawn(
            monkeypatch, _snapshot_with_carrier(carrier),
            review_memory=True, review_skills=False,
        )
        text = _history_text(captured.get("conversation_history", []))
        assert _SUMMARY_MARKER not in text
        assert _TAIL_MARKER in text

    def test_merged_carrier_keeps_live_user_text_only(self, monkeypatch):
        merged = (
            _MERGED_PRIOR_CONTEXT_HEADER + "\n"
            f"actually please record {_LIVE_MERGED_MARKER} as my check name\n"
            + _MERGED_SUMMARY_DELIMITER + "\n"
            + SUMMARY_PREFIX + _summary_body()
        )
        carrier = {
            "role": "user",
            "content": merged,
            COMPRESSED_SUMMARY_METADATA_KEY: True,
            COMPRESSED_SUMMARY_HAS_USER_TURN_KEY: True,
        }
        snapshot = _snapshot_with_carrier(carrier)
        captured = _drive_spawn(
            monkeypatch, snapshot,
            review_memory=True, review_skills=False,
        )
        history = captured.get("conversation_history", [])
        # Single-row emission pins strict alternation: a stub + live_view pair would be
        # two consecutive user rows.
        assert len(history) == len(snapshot)
        text = _history_text(history)
        assert _SUMMARY_MARKER not in text
        assert _LIVE_MERGED_MARKER in text
        assert _TAIL_MARKER in text

    def test_stub_preserves_tool_role_pairing_keys(self, monkeypatch):
        tool_carrier = {
            "role": "tool", "tool_call_id": "call-9", "name": "read_file",
            "content": SUMMARY_PREFIX + _summary_body(),
            COMPRESSED_SUMMARY_METADATA_KEY: True,
        }
        captured = _drive_spawn(
            monkeypatch, _snapshot_with_carrier(tool_carrier),
            review_memory=True, review_skills=False,
        )
        history = captured.get("conversation_history", [])
        text = _history_text(history)
        assert _SUMMARY_MARKER not in text
        stub_rows = [r for r in history if isinstance(r, dict) and r.get("role") == "tool"]
        assert stub_rows and stub_rows[0].get("tool_call_id") == "call-9"
        assert stub_rows[0].get("name") == "read_file"

    def test_stub_preserves_assistant_tool_calls(self, monkeypatch):
        tool_calls = [{"id": "call-1", "function": {"name": "read_file", "arguments": "{}"}}]
        assistant_carrier = {
            "role": "assistant", "content": SUMMARY_PREFIX + _summary_body(),
            "tool_calls": tool_calls, "finish_reason": "tool_calls",
            COMPRESSED_SUMMARY_METADATA_KEY: True,
        }
        captured = _drive_spawn(
            monkeypatch, _snapshot_with_carrier(assistant_carrier),
            review_memory=True, review_skills=False,
        )
        history = captured.get("conversation_history", [])
        assert _SUMMARY_MARKER not in _history_text(history)
        stub_rows = [
            r for r in history
            if isinstance(r, dict) and r.get("role") == "assistant"
            and bg._REVIEW_SUMMARY_EVIDENCE_STUB in _row_text(r)
        ]
        assert stub_rows and stub_rows[0].get("tool_calls") == tool_calls

    def test_stale_api_content_sidecar_does_not_leak_body(self, monkeypatch):
        carrier = _carrier(SUMMARY_PREFIX)
        carrier["api_content"] = carrier["content"]
        captured = _drive_spawn(
            monkeypatch, _snapshot_with_carrier(carrier),
            review_memory=True, review_skills=False,
        )
        history = captured.get("conversation_history", [])
        assert _SUMMARY_MARKER not in _history_text(history)
        stub_rows = [
            r for r in history
            if isinstance(r, dict)
            and bg._REVIEW_SUMMARY_EVIDENCE_STUB in _row_text(r)
        ]
        assert stub_rows and "api_content" not in stub_rows[0]


class TestProjectionScopeControls:
    """R2: only the unattended memory-capable fork loses summary bodies."""

    def test_skills_only_review_keeps_summary_visible(self, monkeypatch):
        captured = _drive_spawn(
            monkeypatch,
            _snapshot_with_carrier(_carrier(SUMMARY_PREFIX)),
            review_memory=False, review_skills=True,
        )
        assert _SUMMARY_MARKER in _history_text(captured.get("conversation_history", []))

    def test_explicit_refine_keeps_summary_visible(self, monkeypatch):
        captured = _drive_spawn(
            monkeypatch,
            _snapshot_with_carrier(_carrier(SUMMARY_PREFIX)),
            review_memory=True, review_skills=False, explicit=True,
        )
        assert _SUMMARY_MARKER in _history_text(captured.get("conversation_history", []))

    def test_memory_disabled_profile_keeps_summary_visible(self, monkeypatch):
        """review_memory=True but the fork cannot write memory -> no capability, no blinding."""
        agent = _bare_agent()
        agent._memory_enabled = False
        captured = _drive_spawn(
            monkeypatch,
            _snapshot_with_carrier(_carrier(SUMMARY_PREFIX)),
            agent=agent, review_memory=True, review_skills=False,
        )
        assert _SUMMARY_MARKER in _history_text(captured.get("conversation_history", []))


class TestRoutedDigestPath:
    def test_digest_carries_no_summary_payload(self, monkeypatch):
        """The routed path digests the projected snapshot: >24 rows so the carrier is collapsed."""
        rows = [
            {"role": "user", "content": "first task"},
            {"role": "assistant", "content": "done"},
            _carrier(SUMMARY_PREFIX),
            {"role": "user", "content": "second task"},
            {"role": "assistant", "content": "also done"},
            {"role": "user", "content": "third task"},
        ]
        for i in range(12):
            rows.append({"role": "user", "content": f"padding turn {i}"})
            rows.append({"role": "assistant", "content": f"padding reply {i}"})
        rows.append({"role": "user", "content": f"final ask mentions {_TAIL_MARKER}"})
        assert len(rows) > 24

        captured = _drive_spawn_routed(
            monkeypatch, rows, review_memory=True, review_skills=False)
        history = captured.get("conversation_history", [])
        assert history and history[0].get("role") == "user"
        digest_text = _row_text(history[0])
        assert "USER:" in digest_text  # the digest really ran; the carrier was collapsed
        # The digest truncates collapsed rows at 300 chars, so the marker alone cannot prove the
        # projected list was digested; the stub's own USER: line can.
        stub = bg._REVIEW_SUMMARY_EVIDENCE_STUB
        assert f"USER: {stub}" in digest_text
        assert _SUMMARY_MARKER not in _history_text(history)
        assert _TAIL_MARKER in _history_text(history)


class TestPassthroughAndToolBoundary:
    def test_snapshot_is_not_mutated(self, monkeypatch):
        """The projection copies; the diff-side snapshot still carries the original carrier."""
        snapshot = _snapshot_with_carrier(_carrier(SUMMARY_PREFIX))
        before = copy.deepcopy(snapshot)
        projected = bg._project_summary_evidence_for_review(snapshot)
        assert snapshot == before
        assert _SUMMARY_MARKER not in _history_text(projected)
        _drive_spawn(
            monkeypatch, snapshot, review_memory=True, review_skills=False)
        assert _SUMMARY_MARKER in _history_text(snapshot)

    def test_empty_and_non_dict_rows_pass_through(self, monkeypatch):
        captured = _drive_spawn(
            monkeypatch, [], review_memory=True, review_skills=False)
        assert captured.get("conversation_history") == []

        captured = _drive_spawn(
            monkeypatch,
            [{"role": "user", "content": "hi"}, 42],
            review_memory=True, review_skills=False,
        )
        history = captured.get("conversation_history", [])
        assert len(history) == 2 and history[1] == 42

    def test_memory_tool_still_writes_direct_evidence(self, monkeypatch, tmp_path):
        """The boundary is evidence visibility, not capability: the real memory tool still
        accepts an add built on a direct user statement inside the same fork run."""
        from tools.memory_tool import memory_tool
        from tools.memory_tool_store import MemoryStore
        from tools.skill_provenance import (
            reset_current_write_origin, reset_review_attended,
            set_current_write_origin, set_review_attended,
        )

        monkeypatch.setenv("HERMES_HOME", str(tmp_path / "home"))
        monkeypatch.setattr("tools.memory_tool.get_memory_dir", lambda: tmp_path)
        store = MemoryStore(memory_char_limit=500, user_char_limit=300)
        store.load_from_disk()

        tool_result = {}

        def run_tool():
            origin_tok = set_current_write_origin("background_review")
            attended_tok = set_review_attended(False)
            try:
                tool_result.update(json.loads(memory_tool(
                    action="add", content=f"user check name: {_TAIL_MARKER}", store=store)))
            finally:
                reset_review_attended(attended_tok)
                reset_current_write_origin(origin_tok)

        captured = _drive_spawn(
            monkeypatch,
            _snapshot_with_carrier(_carrier(SUMMARY_PREFIX)),
            on_run=run_tool,
            review_memory=True, review_skills=False,
        )
        assert _SUMMARY_MARKER not in _history_text(captured.get("conversation_history", []))
        assert tool_result.get("success") is True
        assert any(_TAIL_MARKER in entry for entry in store._entries_for("memory"))
        assert all(_SUMMARY_MARKER not in entry for entry in store._entries_for("memory"))


class TestPromptEvidenceClause:
    """U3: the memory-bearing prompts carry the non-evidence clause as defence in depth."""

    def test_memory_prompts_rule_out_summary_evidence(self):
        for prompt in (bg._MEMORY_REVIEW_PROMPT, bg._COMBINED_REVIEW_PROMPT):
            assert "compaction" in prompt.lower()
            lowered = prompt.lower()
            assert "not" in lowered and "evidence" in lowered

    def test_skill_prompt_carries_no_compaction_clause(self):
        assert "compaction" not in bg._SKILL_REVIEW_PROMPT.lower()
